---
name: Docker build/push action
description: >
  A local composite action for building and pushing docker images.
  Uses docker/login-action, docker/setup-buildx-action and
  docker/build-push-action.

inputs:
  dockerfile:
    description: The Dockerfile to use for building the image.
    required: true
  build-args:
    description: List of build arguments to use when building the image.
    required: false
    default: ''
  target:
    description: Name of target build stage to build.
    required: false
    default: ''
  tags:
    description: List of tags to apply to the built image.
      It is recommended to use docker/metadata-action to generate these.
    required: true
  labels:
    description: List of labels to apply to the built image.
      It is recommended to use docker/metadata-action to generate these.
    required: false
    default: ''
  push:
    description: Set to push the built image to a remote repository
      hosted in registry. Default true.
      (Push is a shorthand for --output=type=registry)
    required: false
    default: 'true'
  load:
    description: Set to keep the built image in the local repository.
      Default false. (Load is a shorthand for --output=type=docker)
    required: false
    default: 'false'
  use_qemu:
    description: Set to use QEMU when building the image. Default false.
    required: false
    default: 'false'
  registry:
    description: Name of the remote registry to push the image to.
      Default docker.io.
    required: false
    default: 'docker.io'
  registry_user:
    description: Username for a user with push access on the remote registry.
      Required if push is true.
    required: false
  registry_token:
    description: Token/password for the user on the the remote registry.
      Required if push is true.
    required: false

runs:
  using: composite
  steps:
    - name: Set up Docker buildx
      # sha for docker/setup-buildx-action@v2 at time of commit.
      uses: docker/setup-buildx-action@4b4e9c3e2d4531116a6f8ba8e71fc6e2cb6e6c8c
    - name: Set up QEMU
      if: ${{ inputs.use_qemu == 'true'}}
      # sha for docker/setup-qemu-action@v2 at time of commit.
      uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18
    - name: Log in to the container registry
      if: ${{ inputs.push == 'true' }}
      # sha for docker/login-action@v2 at time of commit.
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.registry_user }}
        password: ${{ inputs.registry_token }}
    - name: Build and push image to registry
      # sha for docker/build-push-action@v4 at time of commit.
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: .
        push: ${{ inputs.push }}
        load: ${{ inputs.load }}
        file: ${{ inputs.dockerfile }}
        build-args: ${{ inputs.build-args }}
        tags: ${{ inputs.tags }}
        labels: ${{ inputs.labels }}
        target: ${{ inputs.target }}
