#!/bin/bash
# shellcheck disable=SC2001
# Extracts the architecture as the part of the image tag after '-'
AXIS_ARCH=$(echo "$DOCKER_TAG" | sed 's/.*-\(.*\)/\1/')
./build.sh "$AXIS_ARCH" "$IMAGE_NAME"
